export type RadarProject = {
  id: string;
  name: string;
  symbol: string;
  description: string;
  categories: string[];
  stage: "New" | "Growing" | "Mature";
  risk: "Low" | "Medium" | "High";
  tokenAddress?: `0x${string}`;
  baseScanUrl?: string;
  website: string;
  x?: string;
  iconUrl: string;
  accent: string;
};

function favicon(domain: string) {
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;
}

export const radarProjects: RadarProject[] = [
  {
    id: "aerodrome",
    name: "Aerodrome",
    symbol: "AERO",
    description: "Base-native liquidity hub and AMM with vote-escrow incentives.",
    categories: ["DeFi", "DEX", "Liquidity"],
    stage: "Mature",
    risk: "Low",
    tokenAddress: "0x940181a94A35A4569E4529A3CDfB74e38FD98631",
    website: "https://aerodrome.finance",
    x: "https://x.com/AerodromeFi",
    iconUrl: favicon("aerodrome.finance"),
    accent: "from-blue-500 to-cyan-300",
  },
  {
    id: "virtuals",
    name: "Virtuals Protocol",
    symbol: "VIRTUAL",
    description: "AI agent launch and ownership economy built around onchain agents.",
    categories: ["AI", "Social", "Infra"],
    stage: "Growing",
    risk: "Medium",
    tokenAddress: "0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b",
    website: "https://www.virtuals.io",
    x: "https://x.com/virtuals_io",
    iconUrl: favicon("virtuals.io"),
    accent: "from-violet-500 to-fuchsia-300",
  },
  {
    id: "moonwell",
    name: "Moonwell",
    symbol: "WELL",
    description: "Lending and borrowing market for Base and the wider onchain economy.",
    categories: ["DeFi", "Lending", "Yield"],
    stage: "Mature",
    risk: "Low",
    tokenAddress: "0xA88594D404727625A9437C3f886C7643872296AE",
    website: "https://moonwell.fi",
    x: "https://x.com/MoonwellDeFi",
    iconUrl: favicon("moonwell.fi"),
    accent: "from-emerald-500 to-cyan-300",
  },
  {
    id: "degen",
    name: "Degen",
    symbol: "DEGEN",
    description: "Farcaster-native community token and reward economy on Base.",
    categories: ["Social", "Community", "Rewards"],
    stage: "Mature",
    risk: "Medium",
    tokenAddress: "0x4ed4E862860beD51a9570b96d89aF5E1B0Efefed",
    website: "https://www.degen.tips",
    x: "https://x.com/degentokenbase",
    iconUrl: favicon("degen.tips"),
    accent: "from-pink-500 to-amber-300",
  },
  {
    id: "brett",
    name: "Brett",
    symbol: "BRETT",
    description: "One of the largest Base meme communities and culture tokens.",
    categories: ["Meme", "Community", "Social"],
    stage: "Mature",
    risk: "Medium",
    tokenAddress: "0x532f27101965dd16442E59d40670FaF5eBB142E4",
    website: "https://www.basedbrett.com",
    x: "https://x.com/BasedBrett",
    iconUrl: favicon("basedbrett.com"),
    accent: "from-indigo-500 to-blue-300",
  },
  {
    id: "clanker",
    name: "Clanker",
    symbol: "CLANKER",
    description: "Tokenbot and social launch primitive for creating tokens on Base.",
    categories: ["AI", "Social", "Launchpad"],
    stage: "Growing",
    risk: "Medium",
    tokenAddress: "0x1bc0c42215582d5a085795f4badbac3ff36d1bcb",
    website: "https://www.clanker.world",
    x: "https://x.com/clankeronbase",
    iconUrl: favicon("clanker.world"),
    accent: "from-lime-500 to-emerald-300",
  },
  {
    id: "0x",
    name: "0x",
    symbol: "0X",
    description: "Infrastructure for building financial products on crypto rails.",
    categories: ["Infra", "Developer Tool", "DeFi"],
    stage: "Mature",
    risk: "Low",
    website: "https://0x.org",
    x: "https://x.com/0xProject",
    iconUrl: favicon("0x.org"),
    accent: "from-slate-500 to-cyan-300",
  },
  {
    id: "0xppl",
    name: "0xPPL",
    symbol: "PPL",
    description: "Web3 social platform for following onchain activity and trends.",
    categories: ["Consumer", "Social", "Wallet"],
    stage: "Growing",
    risk: "Medium",
    website: "https://0xppl.com",
    x: "https://x.com/0xppl_",
    iconUrl: favicon("0xppl.com"),
    accent: "from-purple-500 to-blue-300",
  },
  {
    id: "0xsplits",
    name: "0xSplits",
    symbol: "SPLITS",
    description: "Modular payment splitting contracts for onchain revenue and expenses.",
    categories: ["Infra", "Developer Tool", "Payments"],
    stage: "Mature",
    risk: "Low",
    website: "https://www.0xsplits.xyz",
    x: "https://x.com/0xSplits",
    iconUrl: favicon("0xsplits.xyz"),
    accent: "from-amber-500 to-orange-300",
  },
  {
    id: "1rpc",
    name: "1RPC",
    symbol: "1RPC",
    description: "Private RPC relay for reducing metadata leakage while using onchain apps.",
    categories: ["Infra", "Node Provider", "Privacy"],
    stage: "Mature",
    risk: "Low",
    website: "https://1rpc.io",
    x: "https://x.com/AutomataNetwork",
    iconUrl: favicon("1rpc.io"),
    accent: "from-cyan-500 to-blue-300",
  },
  {
    id: "20lab",
    name: "20lab",
    symbol: "20LAB",
    description: "No-code token generator and token owner dashboard for multiple chains.",
    categories: ["Infra", "Developer Tool", "Launchpad"],
    stage: "Growing",
    risk: "Medium",
    website: "https://20lab.app/generate/erc20-token/base/",
    iconUrl: favicon("20lab.app"),
    accent: "from-fuchsia-500 to-pink-300",
  },
  {
    id: "3dns",
    name: "3DNS",
    symbol: "3DNS",
    description: "Onchain domain name service for importing or registering real domains.",
    categories: ["Consumer", "NFT", "Identity"],
    stage: "Growing",
    risk: "Medium",
    website: "https://3dns.box",
    x: "https://x.com/3dns_inc",
    iconUrl: favicon("3dns.box"),
    accent: "from-blue-500 to-indigo-300",
  },
  {
    id: "a0x",
    name: "A0x",
    symbol: "A0X",
    description: "No-code platform to build tokenized social media AI agents.",
    categories: ["AI", "Consumer", "Social"],
    stage: "New",
    risk: "Medium",
    website: "https://a0x.co",
    iconUrl: favicon("a0x.co"),
    accent: "from-emerald-500 to-lime-300",
  },
  {
    id: "aave",
    name: "Aave",
    symbol: "AAVE",
    description: "Non-custodial liquidity protocol for supplying and borrowing assets.",
    categories: ["DeFi", "Lending", "Borrowing"],
    stage: "Mature",
    risk: "Low",
    tokenAddress: "0x63706e401c06ac8513145b7687a14804d17f814b",
    website: "https://app.aave.com",
    x: "https://x.com/aave",
    iconUrl: favicon("aave.com"),
    accent: "from-violet-500 to-pink-300",
  },
  {
    id: "across",
    name: "Across Protocol",
    symbol: "ACX",
    description: "Cross-chain bridge optimized for capital efficiency and fast transfers.",
    categories: ["Infra", "Bridge", "DeFi"],
    stage: "Mature",
    risk: "Low",
    website: "https://across.to",
    x: "https://x.com/AcrossProtocol",
    iconUrl: favicon("across.to"),
    accent: "from-lime-500 to-cyan-300",
  },
  {
    id: "add3",
    name: "Add3",
    symbol: "ADD3",
    description: "Smart contract creation and management tooling for web3 projects.",
    categories: ["Infra", "Developer Tool", "Analytics"],
    stage: "Growing",
    risk: "Medium",
    website: "https://add3.io",
    iconUrl: favicon("add3.io"),
    accent: "from-sky-500 to-blue-300",
  },
  {
    id: "agentipy",
    name: "AgentiPy",
    symbol: "AGENTIPY",
    description: "Python framework for connecting AI agents to onchain apps.",
    categories: ["AI", "Infra", "Developer Tool"],
    stage: "New",
    risk: "Medium",
    website: "https://agentipy.fun",
    iconUrl: favicon("agentipy.fun"),
    accent: "from-green-500 to-emerald-300",
  },
  {
    id: "ai-agent-arena",
    name: "AI Agent Arena",
    symbol: "ARENA",
    description: "Prompt battle arena where custom AI agents compete onchain.",
    categories: ["AI", "Consumer", "Gaming"],
    stage: "New",
    risk: "Medium",
    website: "https://play.agent-arena.xyz",
    iconUrl: favicon("play.agent-arena.xyz"),
    accent: "from-red-500 to-fuchsia-300",
  },
  {
    id: "aibased",
    name: "AIBased",
    symbol: "AIBASED",
    description: "AI image generation and dynamic NFT tooling for creators.",
    categories: ["AI", "NFT", "Consumer"],
    stage: "New",
    risk: "Medium",
    website: "https://aibased.app",
    iconUrl: favicon("aibased.app"),
    accent: "from-cyan-500 to-violet-300",
  },
  {
    id: "aitv",
    name: "AITV",
    symbol: "AITV",
    description: "24/7 livestream of intelligent autonomous agents across topics.",
    categories: ["AI", "Consumer", "Social"],
    stage: "New",
    risk: "Medium",
    website: "https://aitv.gg",
    iconUrl: favicon("aitv.gg"),
    accent: "from-orange-500 to-amber-300",
  },
  {
    id: "base-bridge",
    name: "Base Bridge",
    symbol: "BRIDGE",
    description: "Official Base bridge hub for moving assets into and out of Base.",
    categories: ["Bridge", "Official", "Infra"],
    stage: "Mature",
    risk: "Low",
    website: "https://bridge.base.org",
    x: "https://x.com/base",
    iconUrl: favicon("base.org"),
    accent: "from-blue-500 to-sky-300",
  },
  {
    id: "superbridge",
    name: "Superbridge",
    symbol: "SUPER",
    description: "Simple bridge interface for Base and the wider OP Superchain.",
    categories: ["Bridge", "Infra"],
    stage: "Mature",
    risk: "Low",
    website: "https://superbridge.app",
    x: "https://x.com/superbridgeapp",
    iconUrl: favicon("superbridge.app"),
    accent: "from-cyan-500 to-blue-300",
  },
  {
    id: "relay",
    name: "Relay",
    symbol: "RELAY",
    description: "Fast cross-chain bridge and swap routing for Base users.",
    categories: ["Bridge", "Swap", "Infra"],
    stage: "Growing",
    risk: "Low",
    website: "https://www.relay.link/bridge",
    x: "https://x.com/relayprotocol",
    iconUrl: favicon("relay.link"),
    accent: "from-indigo-500 to-cyan-300",
  },
  {
    id: "bridgg",
    name: "Brid.gg",
    symbol: "BRIDGG",
    description: "Bridge interface for Ethereum, Base, and OP Stack networks.",
    categories: ["Bridge", "Infra"],
    stage: "Growing",
    risk: "Low",
    website: "https://www.brid.gg/base",
    iconUrl: favicon("brid.gg"),
    accent: "from-slate-500 to-blue-300",
  },
  {
    id: "garden",
    name: "Garden",
    symbol: "GARDEN",
    description: "Non-custodial Bitcoin bridge for moving BTC liquidity to Base.",
    categories: ["Bridge", "Bitcoin", "Infra"],
    stage: "Growing",
    risk: "Medium",
    website: "https://garden.finance",
    x: "https://x.com/garden_finance",
    iconUrl: favicon("garden.finance"),
    accent: "from-orange-500 to-yellow-300",
  },
  {
    id: "stargate",
    name: "Stargate",
    symbol: "STG",
    description: "Composable liquidity transport protocol for bridging assets across chains.",
    categories: ["Bridge", "DeFi", "Infra"],
    stage: "Mature",
    risk: "Low",
    tokenAddress: "0xE3B53AF74a4BF62Ae5511055290838050bf764Df",
    website: "https://www.stargate.finance",
    x: "https://x.com/StargateFinance",
    iconUrl: favicon("stargate.finance"),
    accent: "from-violet-500 to-indigo-300",
  },
  {
    id: "bungee",
    name: "Bungee",
    symbol: "BUNGEE",
    description: "Bridge and route aggregator for finding efficient cross-chain paths.",
    categories: ["Bridge", "Swap", "Aggregator"],
    stage: "Mature",
    risk: "Low",
    baseScanUrl: "https://basescan.org/address/0x3a23F943181408EAC424116Af7b7790c94Cb97a5",
    website: "https://www.bungee.exchange",
    x: "https://x.com/BungeeExchange",
    iconUrl: favicon("bungee.exchange"),
    accent: "from-fuchsia-500 to-purple-300",
  },
  {
    id: "orbiter",
    name: "Orbiter Finance",
    symbol: "ORBITER",
    description: "Cross-rollup bridge and swap platform supporting Base routes.",
    categories: ["Bridge", "Swap", "Infra"],
    stage: "Mature",
    risk: "Low",
    website: "https://www.orbiter.finance",
    x: "https://x.com/Orbiter_Finance",
    iconUrl: favicon("orbiter.finance"),
    accent: "from-blue-500 to-violet-300",
  },
  {
    id: "uniswap",
    name: "Uniswap",
    symbol: "UNI",
    description: "Leading DEX interface for swaps and liquidity across Base and other chains.",
    categories: ["DeFi", "DEX", "Swap"],
    stage: "Mature",
    risk: "Low",
    tokenAddress: "0xc3de830EA07524a0761646a6a4e4be0e114a3C83",
    website: "https://app.uniswap.org",
    x: "https://x.com/Uniswap",
    iconUrl: favicon("uniswap.org"),
    accent: "from-pink-500 to-fuchsia-300",
  },
  {
    id: "sushi",
    name: "Sushi",
    symbol: "SUSHI",
    description: "Swap interface with support for Base swaps, limit orders, and cross-chain routes.",
    categories: ["DeFi", "DEX", "Swap"],
    stage: "Mature",
    risk: "Low",
    tokenAddress: "0x0214d750cfccec11e8d1078c863256df4dce6ec4",
    website: "https://sushi.com/base/swap",
    x: "https://x.com/SushiSwap",
    iconUrl: favicon("sushi.com"),
    accent: "from-rose-500 to-pink-300",
  },
  {
    id: "baseswap",
    name: "BaseSwap",
    symbol: "BSX",
    description: "Base-native DEX with V2/V3 liquidity, pools, and swap routing.",
    categories: ["DeFi", "DEX", "Swap"],
    stage: "Growing",
    risk: "Medium",
    tokenAddress: "0xd47f3e45b23b7594f5d5e1ccfde63237c60be49e",
    website: "https://baseswap.fi",
    x: "https://x.com/BaseSwap_Fi",
    iconUrl: favicon("baseswap.fi"),
    accent: "from-blue-500 to-emerald-300",
  },
  {
    id: "odos",
    name: "Odos",
    symbol: "ODOS",
    description: "Smart order routing and swap aggregation across Base liquidity venues.",
    categories: ["DeFi", "Swap", "Aggregator"],
    stage: "Mature",
    risk: "Low",
    tokenAddress: "0xca73ed1815e5915489570014e024b7EbE65dE679",
    website: "https://app.odos.xyz",
    x: "https://x.com/odosprotocol",
    iconUrl: favicon("odos.xyz"),
    accent: "from-cyan-500 to-teal-300",
  },
  {
    id: "matcha",
    name: "Matcha",
    symbol: "MATCHA",
    description: "0x-powered DEX aggregator for finding competitive swap routes.",
    categories: ["DeFi", "Swap", "Aggregator"],
    stage: "Mature",
    risk: "Low",
    website: "https://matcha.xyz",
    x: "https://x.com/matchaxyz",
    iconUrl: favicon("matcha.xyz"),
    accent: "from-green-500 to-lime-300",
  },
  {
    id: "morpho",
    name: "Morpho",
    symbol: "MORPHO",
    description: "Lending infrastructure and vault layer used by multiple Base money markets.",
    categories: ["DeFi", "Lending", "Yield"],
    stage: "Mature",
    risk: "Low",
    tokenAddress: "0xBAa5CC21fd487B8Fcc2F632f3F4E8D37262a0842",
    website: "https://app.morpho.org",
    x: "https://x.com/MorphoLabs",
    iconUrl: favicon("morpho.org"),
    accent: "from-blue-500 to-indigo-300",
  },
  {
    id: "seamless",
    name: "Seamless Protocol",
    symbol: "SEAM",
    description: "Base-native lending, borrowing, and leverage strategies built on Morpho.",
    categories: ["DeFi", "Lending", "Yield"],
    stage: "Growing",
    risk: "Medium",
    tokenAddress: "0x1C7a460413dD4e964f96D8dFC56E7223cE88CD85",
    website: "https://www.seamlessprotocol.com",
    x: "https://x.com/SeamlessFi",
    iconUrl: favicon("seamlessprotocol.com"),
    accent: "from-emerald-500 to-lime-300",
  },
  {
    id: "compound",
    name: "Compound",
    symbol: "COMP",
    description: "Established lending protocol with Base market access for supplied assets.",
    categories: ["DeFi", "Lending", "Borrowing"],
    stage: "Mature",
    risk: "Low",
    tokenAddress: "0x9e1028F5F1D5eDE59748FFceE5532509976840E0",
    website: "https://app.compound.finance",
    x: "https://x.com/compoundfinance",
    iconUrl: favicon("compound.finance"),
    accent: "from-emerald-500 to-green-300",
  },
];
